api_platform:
    title: '油画api'
    enable_swagger_ui: false
    formats:
        json:
            mime_types: ['application/json']

    mapping:
        paths:
            # - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform/resources'

    collection:
        # The default order of results.
        order: 'ASC'
        order_parameter_name: 'order'

    exception_to_status:
        # With a status code.
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
