services:
  admin.banner:
    class: App\Admin\BannerAdmin
    arguments: [~, App\Entity\Banner, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: '运营管理', label: '轮播图管理' }
    calls:
      - [ setUploadableListener, [ "@gedmo.listener.uploadable" ] ]
    public: true

  admin.goods:
    class: App\Admin\GoodsAdmin
    arguments: [~, App\Entity\Goods, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: '商品管理', label: '商品' }
    calls:
      - [ setUploadableListener, [ "@rip.listener.uploadable" ] ]
    public: true

  admin.classify_goods:
    class: App\Admin\ClassifyGoodsAdmin
    arguments: [~, App\Entity\ClassifyGoods, PicossSonataExtraAdminBundle:ExtraAdmin]
    tags:
      - { name: sonata.admin, manager_type: orm, group: '商品管理', label: '商品分类' }
    calls:
      - [ setUploadableListener, [ "@gedmo.listener.uploadable" ] ]
    public: true

  admin.goods_banner:
    class: App\Admin\GoodsBannerAdmin
    arguments: [~, App\Entity\GoodsBanner, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: admin, label: GoodsBanner, show_in_dashboard: false }
    public: false
