App\Entity\Consumer:
    attributes:
        id:
            groups: ['consumer:item:read']

        image:
            groups: ['consumer:item:read', 'consumer:item:write']

        nickName:
            groups: ['consumer:item:read', 'consumer:item:write']

        # type:
        #     groups: ['consumer:item:read']

        sex:
            groups: ['consumer:item:read', 'consumer:item:write']

        member:
            groups: ['consumer:item:read']

        firstLoginAt:
            groups: ['consumer:item:read']

        lastLoginAt:
            groups: ['consumer:item:read']
